<?php
return [
    'siteName' => 'Pivot',
    'adminEmail' => 'test@test.com',
    'supportEmail' => 'test@test.com',
    'user.passwordResetTokenExpire' => 3600,
    'arrPaging' => ['500' => 'All', '5' => '5', '10' => '10', '15' => '15', '20' => '20', '25' => '25', '30' => '30', '35' => '35', '50' => '50', '100' => '100'],
    'arrPriority' => ['low' => 'Low', 'normal' => 'Normal', 'high' => 'High'],
    'arrslaplan' => ['system default' => 'System Default', '1 hours' => '1 Hours', '2 hours' => '2 Hours', 'third' => 'Third Party Service'],
    'arrTicketStaus' => ['open' => 'Open', 'answered' => 'Answered', 'overdue' => 'Overdue','closed'=>'Closed'],
    'arrDeptslaTime' => ['' => 'SLA Time', '1 hours' => '1 Hours', '2 hours' => '2 Hours', '6 hours' => '6 Hours', '10 hours' => '10 Hours', '24 hours' => '24 Hours'],
    'arrDeptAccess' => ['1' => 'All Tickets', '2' => 'Assigned Tickets Only', '3' => 'Admin'],
    'arrCategoryStatus' => ['1' => 'Active', '0' => 'Inactive'],
    'arrOrderStatus' => ['4' => 'Cancelled', '3' => 'Completed','2' =>'Posted','1' => 'Pending'],
    'arrCategory' => ['0' => 'Weekly', '1' => 'Monthly'],
    'equipmentType' => ['2' => 'Pump 28', '1' => 'Water Pump','0' =>'Pivot'],
    'arrAdminStatus' => ['0' => 'Deactive', '10' => 'Active'],
    'stopAndStart' => ['0' => 'Stop', '1' => 'Start'],
	'loginPageMessage'=>'',
];
